use_aws: false
aws_region: "eu-north-1"
cloudwatch_namespace: "MyApp/Feedback"
cloudwatch_metric_name: "NegativeFeedbackCount"
negative_feedback_limit: 5
negative_feedback_window_minutes: 5
model_dir: saved_models/final_distilbert_model