name: Deploy FastAPI to AWS EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Lister les fichiers pour vérification
    - name: List project files
      run: ls -R

    # Étape 3 : Construire l'image Docker
    - name: Build Docker image
      run: docker build -t fastapi-app .

    # Étape 4 : Exécuter les tests dans le conteneur Docker
    - name: Run tests in Docker
      run: |
        docker run --rm fastapi-app test
      # Si les tests échouent, GitHub Actions arrêtera automatiquement le workflow.

    # Étape 5 : Se connecter à Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Étape 6 : Pousser l'image sur Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker tag fastapi-app dralakh/airparadis:latest && docker push dralakh/airparadis:latest

    # Étape 7 : Déployer sur EC2
    - name: Add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_KEY }}" > ndevilder-airParadis.pem
        chmod 600 ndevilder-airParadis.pem
        ssh -o StrictHostKeyChecking=no -i ndevilder-airParadis.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        sudo docker stop fastapi-app || true
        sudo docker rm fastapi-app || true
        sudo docker pull dralakh/airparadis:latest
        sudo docker run -d --name fastapi-app -p 80:80 dralakh/airparadis:latest
        sudo docker ps
        EOF
