name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Verify EC2_HOST
      run: echo "EC2_HOST is set to: $EC2_HOST"

    - name: Create SSH directory
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Add EC2 to known_hosts
      run: |
        if [ -z "$EC2_HOST" ]; then
          echo "Error: EC2_HOST is not set or empty."
          exit 1
        fi
        ssh-keyscan -p 22 -H $EC2_HOST >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > ec2-key.pem
        chmod 600 ec2-key.pem
        scp -i ec2-key.pem -r ./* $EC2_USER@$EC2_HOST:/home/$EC2_USER/app
        ssh -i ec2-key.pem $EC2_USER@$EC2_HOST << 'EOF'
          sudo docker stop fastapi-app || true
          sudo docker rm fastapi-app || true
          cd /home/$EC2_USER/app
          sudo docker build -t fastapi-app .
          sudo docker run -d -p 80:8000 --name fastapi-app fastapi-app
        EOF
