name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupération du code
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List project files
      run: ls -R

    # Étape 2 : Installer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        pip install httpx

    # Étape 4 : Ajouter PYTHONPATH pour trouver les modules
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    # Étape 5 : Créer un fichier config.yaml pour les tests
    - name: Create config.yaml for tests
      run: |
        echo "negative_feedback_limit: 10" > config.yaml
        echo "negative_feedback_window_minutes: 5" >> config.yaml
        echo "use_aws: false" >> config.yaml
        echo "model_dir: distilbert-base-uncased" >> config.yaml
        echo "cloudwatch_metric_name: NegativeFeedbackCount" >> config.yaml
        echo "cloudwatch_namespace: MyApp/Feedback" >> config.yaml

    - name: Create static directory for tests
      run: mkdir -p static


    # Étape 6 : Vérifier les packages installés
    - name: Check installed packages
      run: pip list

    # Étape 7 : Exécuter les tests avec couverture
    - name: Run Pytest
      run: pytest --cov=. --cov-report=xml

    # Étape 8 : Installer le client SSH
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    # Étape 9 : Créer le fichier de clé SSH
    - name: Create SSH key file
      run: |
        echo "${{ secrets.EC2_KEY }}" > ndevilder-airParadis.pem
        chmod 600 ndevilder-airParadis.pem

    # Étape 10 : Ajouter EC2 à known_hosts
    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # Étape 11 : Vérifier la connexion SSH
    - name: Test SSH Connection
      run: |
        ssh -i ndevilder-airParadis.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

    # Étape 12 : Créer le répertoire de l'application sur EC2
    - name: Create App Directory on EC2
      run: |
        ssh -i ndevilder-airParadis.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p /home/${{ secrets.EC2_USER }}/app"

    # Étape 13 : Transférer les fichiers vers EC2
    - name: Transfer Files to EC2
      run: |
        scp -i ndevilder-airParadis.pem -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app

    # Étape 14 : Déployer l'application sur EC2
    - name: Deploy Application on EC2
      run: |
        ssh -i ndevilder-airParadis.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo docker stop fastapi-app || true
          sudo docker rm fastapi-app || true
          cd /home/${{ secrets.EC2_USER }}/app || exit 1
          sudo docker build -t fastapi-app .
          sudo docker run -d --name fastapi-app -p 80:80 fastapi-app
        EOF
