name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer la connexion SSH
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > ec2-key.pem
        chmod 600 ec2-key.pem
        scp -i ec2-key.pem -r ./* $EC2_USER@$EC2_HOST:/home/ec2-user/app
        ssh -i ec2-key.pem $EC2_USER@$EC2_HOST << 'EOF'
          sudo docker stop fastapi-app || true
          sudo docker rm fastapi-app || true
          cd /home/ec2-user/app
          sudo docker build -t fastapi-app .
          sudo docker run -d -p 80:8000 --name fastapi-app fastapi-app
        EOF

